---
apiVersion: v2
description: l2-rpc helm chart
name: l2-rpc
version: 0.0.1
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-sre
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
