---
apiVersion: v2
description: event-watcher helm charts
name: event-watcher
version: 0.0.1
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-sre
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: "file://../../../common-lib/"
    version: 1.5.1
