---
apiVersion: v2
description: bridge-history-fetcher helm charts
name: bridge-history-fetcher
version: 0.0.10
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
  - name: external-secrets-lib
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 0.0.3
