---
apiVersion: v2
name: external-secrets-lib
description: External secrets function library for Helm charts
type: library
version: 0.0.2
kubeVersion: ">=1.22.0-0"
keywords:
  - external-secrets
  - secret-store
  - library
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
