---
apiVersion: v2
description: helm chart to deploy grafana, prometheus and loki to monitor scroll-sdk
name: scroll-monitor
version: 0.1.0
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
dependencies:
  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: 8.5.12
    condition: grafana.enabled
  - name: loki
    repository: "https://grafana.github.io/helm-charts"
    version: 6.10.2
    condition: loki.enabled
  - name: kube-prometheus-stack
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 59.0.0
    condition: kube-prometheus-stack.enabled
  - name: promtail
    repository: "https://grafana.github.io/helm-charts"
    version: 6.16.5
    condition: promtail.enabled
