global:
  fullnameOverride: l2-bootnode-1

envFrom:
  - configMapRef:
      name: l2-bootnode-1-env

initContainers:
  wait-for-l1:
    image: scrolltech/scroll-alpine:v0.0.1
    command:
      - /bin/sh
      - -c
      - /wait-for-l1.sh $L2GETH_L1_ENDPOINT
    envFrom:
      - configMapRef:
          name: l2-bootnode-1-env
    volumeMounts:
      - name: wait-for-l1-script
        mountPath: /wait-for-l1.sh
        subPath: wait-for-l1.sh

persistence:
  env:
    enabled: true
    type: configMap
    mountPath: /config/
    name: l2-bootnode-1-env

configMaps:
  env:
    enabled: true
    data:
      CHAIN_ID: ""
      L2GETH_L1_ENDPOINT: ""
