---
apiVersion: v2
description: admin-system-cron helm charts
name: admin-system-cron
version: 0.0.1
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: weichi@scroll.io
dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
  - name: external-secrets-lib
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 0.0.3
