global:
  nameOverride: &app_name frontends
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: deployment

image:
  repository: scrolltech/frontends
  pullPolicy: Always
  tag: 2.2.17

command:
  - "/bin/bash"
  - "-cx"
  - |
    awk 'NF {gsub(/ /, ""); print "export " $0}' /app/conf/frontend-config > /usr/share/nginx/html/.env
    source /usr/share/nginx/html/.env
    sed -i "s|src=\"/runtime-env.js\"|src=\"/runtime-env.js?rand=$RANDOM\"|" index.html
    exec /usr/local/bin/entrypoint.sh

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

persistence:
  *app_name:
    enabled: true
    type: configMap
    mountPath: /app/conf/
    name: frontends-config

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 80

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

ingress:
  main:
    enabled: true
    primary: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: frontends.scrollsdk
        paths:
          - path: /
            pathType: Prefix
