---
apiVersion: v2
description: l2-bootnode helm chart
name: l2-bootnode
version: 0.0.1
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
  - name: external-secrets-lib
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 0.0.2
