global:
  isStandalone: true

controller:
  replicas: 2

envFrom:
  - secretRef:
      name: coordinator-cron-secret-env

initContainers:
  1-check-postgres-connection:
    image: atkrad/wait4x:latest
    args:
      - postgresql
      - $(SCROLL_COORDINATOR_DB_DSN)
      - --timeout
      - "0"
    envFrom:
      - secretRef:
          name: coordinator-cron-secret-env

externalSecrets:
  coordinator-cron-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/coordinator-cron-secret-env
          property: SCROLL_COORDINATOR_DB_DSN
        secretKey: SCROLL_COORDINATOR_DB_DSN
      - remoteRef:
          key: scroll/coordinator-cron-secret-env
          property: SCROLL_COORDINATOR_AUTH_SECRET
        secretKey: SCROLL_COORDINATOR_AUTH_SECRET
    refreshInterval: 2m
    serviceAccount: external-secrets
