global:
  nameOverride: &app_name bridge-history-api
  fullnameOverride: *app_name

controller:
  replicas: 1
  strategy: RollingUpdate
  type: deployment

image:
  repository: scrolltech/bridgehistoryapi-api
  pullPolicy: Always
  tag: v4.4.72

command:
  [
    "/bin/sh",
    "-c",
    "bridgehistoryapi-api --config /app/conf/bridge-history-api-config.json --metrics --metrics.addr 0.0.0.0 --metrics.port ${METRICS_PORT} --log.debug",
  ]

env:
  - name: METRICS_PORT
    value: "8090"

envFrom:
  - configMapRef:
      name: bridge-history-api-env

initContainers:
  1-wait-for-l1:
    image: scrolltech/scroll-alpine:v0.0.1
    command:
      - /bin/sh
      - -c
      - /wait-for-l1.sh $SCROLL_L1_RPC
    envFrom:
      - configMapRef:
          name: bridge-history-api-env
    volumeMounts:
      - name: wait-for-l1-script
        mountPath: /wait-for-l1.sh
        subPath: wait-for-l1.sh

  2-wait-for-l2-sequencer:
    image: atkrad/wait4x:latest
    args:
      - http
      - $(SCROLL_L2_RPC)
      - --expect-status-code
      - "200"
      - --timeout
      - "0"
    envFrom:
      - configMapRef:
          name: bridge-history-api-env

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 8080
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

persistence:
  bridge-history-api:
    enabled: true
    type: configMap
    mountPath: /app/conf/
    name: bridge-history-api-config
  wait-for-l1-script:
    enabled: true
    type: configMap
    name: wait-for-l1-script
    defaultMode: "0777"

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "500Mi"
    cpu: "100m"

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/health"
      port: 8090

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

additionalContainers:
  redis:
    name: redis
    image: redis

ingress:
  main:
    enabled: true
    primary: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: bridge-history-api.scrollsdk
        paths:
          - path: /
            pathType: Prefix

serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-sdk
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s

scrollConfig: |
  {}
