apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: scroll-smart-contracts-config
data:
{{ (.Files.Glob "config.toml").AsConfig | indent 2 }}
{{ (.Files.Glob "config-contracts.toml").AsConfig | indent 2 }}