{{- if index .Values "balance-checker" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: balance-checker-config
data:
{{ (.Files.Glob "balance-checker-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: balance-checker-env
data:
{{ (.Files.Glob "configs/balance-checker.env").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "blockscout" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: blockscout-env
data:
{{ .Files.Get "configs/blockscout.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "bridge-history-api" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: bridge-history-config
data:
{{ (.Files.Glob "bridge-history-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: bridge-history-api-env
data:
{{ .Files.Get "configs/bridge-history-api.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "bridge-history-fetcher" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: bridge-history-fetcher-env
data:
{{ .Files.Get "configs/bridge-history-fetcher.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "chain-monitor" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: chain-monitor-config
data:
{{ (.Files.Glob "chain-monitor-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: chain-monitor-env
data:
{{ .Files.Get "configs/chain-monitor.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "coordinator-api" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: coordinator-config
data:
{{ (.Files.Glob "coordinator-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: coordinator-env
data:
{{ .Files.Get "configs/coordinator.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "contracts" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: contracts-env
data:
{{ .Files.Get "configs/contracts.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "event-watcher" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: event-watcher-env
data:
{{ .Files.Get "configs/event-watcher.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "frontends" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: frontends-config
data:
{{ (.Files.Glob ".env.frontend").AsConfig | indent 2 }}
---
{{- end }}
{{- if index .Values "gas-oracle" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: gas-oracle-env
data:
{{ .Files.Get "configs/gas-oracle.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "l1-devnet" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l1-devnet-env
data:
{{ .Files.Get "configs/l1-devnet.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "l1-explorer" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l1-explorer-env
data:
{{ .Files.Get "configs/l1-explorer.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-bootnode" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-bootnode-env
data:
{{ .Files.Get "configs/l2-bootnode.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-rpc" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-rpc-env
data:
{{ .Files.Get "configs/l2-rpc.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "l2-sequencer" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: l2-sequencer-env
data:
{{ .Files.Get "configs/l2-sequencer.env" | indent 2 }}
---
{{- end }}
{{- if index .Values "rollup-node" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: rollup-node-config
data:
{{ (.Files.Glob "rollup-config.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-stack.labels" $ | nindent 4 }}
  name: rollup-node-env
data:
{{ .Files.Get "configs/rollup-node.env" | indent 2 }}
---
{{- end }}